#!/bin/bash
cut -f1 -d$'\t' | sort | uniq -c | tr -s ' ' | sort -t' ' -k1 -nr | head -11 | cut -d' ' -f3
Write a script that parses web servers logs in TSV format as input and displays the 11 hosts or IP addresses which did the most requests.
